CREATE TABLE BRAND (
 id INT AUTO_INCREMENT PRIMARY_KEY,
 NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE COLOR (
 id INT AUTO_INCREMENT PRIMARY_KEY,
 NAME VARCHAR2(100) NOT NULL,
 CODE VARCHAR2(10) NOT NULL
);